### ISSUE TITLE
iam_role name override

### ISSUE THREAD

**Issue by naseemkullah** [cloudposse/terraform-aws-iam-role#51]
## Describe the Feature

When using this module to deploy to multiple regions, there is a naming conflict since the iam role must be unique

## Expected Behavior

Id like to be able to override the iam role name with a parametrized name so that i can deploy to multiple regions

## Use Case

Actually using the AWS config module, thats where i hit this bug. Will bubble up this feat to it once implemented here.

Worth noting, variable description already claims that `var.name` is the fallback, though not implemented

https://github.com/cloudposse/terraform-aws-iam-role/blob/0c6cbfc39147f8413d955153362dfdc800c8cf4d/variables.tf#L7

**Comment by naseemkullah** [comment]
Nevermind, see https://github.com/cloudposse/terraform-aws-iam-role/pull/52#issuecomment-1286038339

**Comment by nitrocode** [comment]
Turns out you can do this using the `var.use_fullname` input which was introduced years ago in this PR https://github.com/cloudposse/terraform-aws-iam-role/pull/8

Set it to `false` and the `name` input will be the name of the role.

https://github.com/cloudposse/terraform-aws-iam-role/blob/871cb1253d430131daf316955ec3664a0522d0cb/variables.tf#L1-L9

https://github.com/cloudposse/terraform-aws-iam-role/blob/871cb1253d430131daf316955ec3664a0522d0cb/main.tf#L37-L39
